config/routes.rb
ExcelTestApp::Application.routes.draw do
  
  
  resources :people do
    get "load_from_excel", :on => :collection
    get "load_from_excel_select_column", :on => :collection
    get "upload",  :on => :collection
    get "upload_ajax",  :on => :collection
    get "save_many_people",  :on => :collection
    get "delayed_job", :on => :collection
    post "store_excel_file",  :on => :collection
    post "store_excel_file_ajax",  :on => :collection
    post "parse_save_from_excel",  :on => :collection
    post "parse_save_from_excel_select_column",:on => :collection 
    post "upload_and_validate",  :on => :collection
    post "upload_select_column",  :on => :collection
    
  end

   root :to => 'people#index'
  
   resources :photos do
     post "hola", :on => :collection
     post "upload_select_column", :on => :member
   end
   
   
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExcelTestApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to "load_from_excel", load_from_excel_people_path %> |
<%= link_to "upload", upload_people_path%> |
<%= link_to "Upload Many People", save_many_people_people_path %> |
<%= link_to "people", people_path%> |
<%= link_to "Load from excel with select column",  load_from_excel_select_column_people_path %> |
<%= link_to "Upload ajax", upload_ajax_people_path%>  |
<%= link_to "Delayed Job", delayed_job_people_path%>

<% unless flash[:notice].nil? %>    
      <%= flash[:notice] %>
  <% end %>

<%= yield %>

</body>
</html>